# Numpy Operations

## Arithmetic
Basic arithmetic operations: +,-,*,/,%,//,**, Can be performed like arrays arithmetic, or scalar with array arithmetic.

In [1]:
import numpy as np

In [2]:
arr=np.arange(0,5)
arr

array([0, 1, 2, 3, 4])

In [3]:
arr+arr

array([0, 2, 4, 6, 8])

In [4]:
arr-arr

array([0, 0, 0, 0, 0])

In [5]:
arr*arr

array([ 0,  1,  4,  9, 16])

In [6]:
#Warning on division by zero
#Division by zero replaced with nan
arr/arr

C:\Users\SHUBHAM\AppData\Local\Temp\ipykernel_11760\2569510854.py:3: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.])

In [7]:
arr//arr

C:\Users\SHUBHAM\AppData\Local\Temp\ipykernel_11760\3990451985.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  arr//arr


array([0, 1, 1, 1, 1], dtype=int32)

In [8]:
arr%arr

C:\Users\SHUBHAM\AppData\Local\Temp\ipykernel_11760\2578260503.py:1: RuntimeWarning: divide by zero encountered in remainder
  arr%arr


array([0, 0, 0, 0, 0], dtype=int32)

In [9]:
arr**arr

array([  1,   1,   4,  27, 256], dtype=int32)

## Some Universal Array Functions

In [10]:
np.sort(arr)

array([0, 1, 2, 3, 4])

In [11]:
#For square root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [12]:
#For exponential
np.exp(arr)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [13]:
np.max(arr)#same as arr.max()

4

In [14]:
np.log(arr)

C:\Users\SHUBHAM\AppData\Local\Temp\ipykernel_11760\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [15]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [16]:
np.log10(arr)

C:\Users\SHUBHAM\AppData\Local\Temp\ipykernel_11760\2153533263.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(arr)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999])

In [17]:
np.log10(2)

0.3010299956639812