## NumPy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr=np.arange(1,17)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

### Brackets Indexing and selections

In [3]:
arr[5]

6

In [4]:
arr[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

## Indexing a 2D arrays(matrices)
Using one subscript comma approch i.e arr_2d[row,col]

In [5]:
arr_2d = np.array(([3,6,9],[10,15,20],[20,25,30],[90,67,56]))
arr_2d

array([[ 3,  6,  9],
       [10, 15, 20],
       [20, 25, 30],
       [90, 67, 56]])

In [6]:
       #0   1   2
    #0[ 3,  6,  9]
    #1[10, 15, 20]
    #2[20, 25, 30]
    #3[90, 67, 56]

In [7]:
arr_2d[2]#2nd row

array([20, 25, 30])

In [8]:
#Indexing multiple rows
arr_2d[2:3]

array([[20, 25, 30]])

In [9]:
#Format is arr_2d[row][col]  or arr_2d[row,col]
#Getting individual element value
arr_2d[1,1]

15

In [10]:
#2D array silicing
#shape (2,2)from top right corner
arr_2d[:2,1:]#before , it consider as rows range and after the , consider as column range
# row=0-1 and column=1- last

array([[ 6,  9],
       [15, 20]])

In [11]:
arr_2d[2: ,1:]

array([[25, 30],
       [67, 56]])

In [12]:
#Shape bottom row
arr_2d[2:5,4:7]#if not present it don't give error but give empty array

array([], shape=(2, 0), dtype=int32)

In [13]:
arr_2d=np.arange(16)
arr_2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
new=arr_2d.reshape(4,4)
new

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
new[2:4,1:2]

array([[ 9],
       [13]])

## Selections
Selecting/Filtering data based on some conditions.

In [16]:
arr1=np.arange(1,21)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
arr1>7#it give the output in boolen

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [18]:
arr1[arr1>7]#if actual element value we want then use [condition]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [19]:
arr1[arr1==12]

array([12])

In [20]:
arr1[arr1<=5]

array([1, 2, 3, 4, 5])

In [21]:
arr1[arr1!=10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [22]:
arr1[arr1<15]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## np.where() function

### Syntax= numpy.where(condition[x,y])
   
   It returns the indices of element in an input array where the given condition is satisfied.
   
   If both x and y are satisfied,the output array contains elements of x where condition is True,and elements from y elsewhere.

In [23]:
np.where(arr1>7)#index

(array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int64),)

In [24]:
arr1[np.where(arr1>7)]#value

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [25]:
np.where(arr1>7,arr1,2)#1st argument=condition , 2nd argument=in such array,  3rd argument=replace by that 

array([ 2,  2,  2,  2,  2,  2,  2,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])