# NumPy

## Installing NumPy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


## Importing NumPy

In [2]:
import numpy as np

## Why NumPy

In [3]:
Distance=[100,90,100,180]
Time=[12,9,21,18]

In [4]:
Speed=Distance/Time
Speed

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [5]:
Distance=[100,90,100,180]
Time=[12,9,21,18]
new=[]
for j in Distance:
    for i in Time:
        speed=j/i
    new.append(speed)
    print("Speed= ", speed)    

Speed=  5.555555555555555
Speed=  5.0
Speed=  5.555555555555555
Speed=  10.0


In [6]:
Distance=[100,90,100,180]
Time=[12,9,21,18]
speed=list(map(lambda x,y:x/y,Distance,Time))
speed

[8.333333333333334, 10.0, 4.761904761904762, 10.0]

In [7]:
#Converting existing data type into numpy array

#new array=np.array(list)
Distance_array=np.array(Distance)
print(Distance_array)
Time_array=np.array(Time)
print(Time_array)

[100  90 100 180]
[12  9 21 18]


In [8]:
Speed=Distance_array/Time_array
Speed

array([ 8.33333333, 10.        ,  4.76190476, 10.        ])

In [9]:
type(Speed)

numpy.ndarray

In [10]:
type(Distance_array)

numpy.ndarray

## Case 1: Easy Operations

In [11]:
#By traditional way
list1 = list(range(1,50,2))
N=len(list1)
print(list1)
for i in range(N):
    list1[i]=list1[i]+5
print(list1)    

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]
[6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54]


In [12]:
#By numpy 
arr1=np.arange(1,50,2)
print(arr1)
arr1=arr1+5
print(arr1)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
[ 6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52
 54]


## Case 2: Speed

In [13]:
import random

In [14]:
%%time
for j in range(100):
    list1 = list(range(1,100,3))
#     print(list1)
    list2 = list(range(2,101,3))
#     print(list2)
    list1 + list2#Combine both list
    list3 = []
    for i in range(len(list1)):
        list3.append(list1[i]+list2[i])#it add the element of both list
print(list3)

[3, 9, 15, 21, 27, 33, 39, 45, 51, 57, 63, 69, 75, 81, 87, 93, 99, 105, 111, 117, 123, 129, 135, 141, 147, 153, 159, 165, 171, 177, 183, 189, 195]
Wall time: 3 ms


In [15]:
%%time
for x in range(100):
    a = np.arange (1,100,3)
    b = np.arange (2,101,3)
    c = a+b
print(c)   

[  3   9  15  21  27  33  39  45  51  57  63  69  75  81  87  93  99 105
 111 117 123 129 135 141 147 153 159 165 171 177 183 189 195]
Wall time: 999 µs


## 3: Memory

In [16]:
import sys

python_list=[10,20,30,40,50]
numpy_array=np.array([10,20,30,40,50])

sizeof_python_list=sys.getsizeof(1)*len(python_list)#20 byte
sizeof_numpy_array=numpy_array.itemsize*numpy_array.size
print("size of python list",sizeof_python_list)
print("size of Numpy Array",sizeof_numpy_array)

size of python list 140
size of Numpy Array 20


In [17]:
print(sys.getsizeof(1))
print(len(python_list))

28
5


In [18]:
print(numpy_array.itemsize)#4byte 
print(numpy_array.size)# 5byte

4
5


## NumPy Arrays
    Numpy arrays essentially come in two flavors:vectors and matices.Vectors re strictly 1-D arrays and matrices are 2-D

## Various ways to create NumPy Arrays

# 1. From a normal Python List
We can create a NumPy array by directly converting a list or list of lists:

In [19]:
list=[1,2,3]
print(list)
np.array(list)

[1, 2, 3]


array([1, 2, 3])

In [20]:
matrix1=[[10,20,30],[40,50,60],[70,80,90]]
print(matrix1)
np.array(matrix1)#When we pass nested list into array it give a matix

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [21]:
np.matrix(matrix1)#Not Recommneded

matrix([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])

# 2. Using Built-in methods
 There are many built-in method to generate NumPy array

## a. arange
  Return a range of value for the specific interval.

In [22]:
np.arange(0,18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [23]:
np.arange(0,100,10)#first argument=start value   2nd argument=stoping value   3rd argument=step size

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [24]:
np.arange(20,1,-2)#if we use negative step function then 1st argument is always larger and  2nd argument be smaller 

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [25]:
np.arange(-1,4,1)

array([-1,  0,  1,  2,  3])

In [26]:
np.arange(1,20,-2)

array([], dtype=int32)

## b. zeros and ones
Generte arrays of zeros and ones.

In [27]:
np.zeros(4,dtype=int)

array([0, 0, 0, 0])

In [28]:
np.zeros((4,4))#argument is tuple,is tuple we need to specify the number of rows and column

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.zeros((4,4),dtype=np.int64)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [30]:
np.ones(3)

array([1., 1., 1.])

In [31]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [32]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

## c. linspace
Returns evenly spaces numbers over a specified interval.

In [33]:
np.linspace(1,10,2)#1st argument=start value  2nd argument=stop value 3rd argument=total number to generate by equal distance

array([ 1., 10.])

In [34]:
np.linspace(2,50,10)# . is float value  and 2nd argument is also consider (n)

array([ 2.        ,  7.33333333, 12.66666667, 18.        , 23.33333333,
       28.66666667, 34.        , 39.33333333, 44.66666667, 50.        ])

## d. eye
Create an identity matrix.

In [35]:
np.eye(2,dtype=int)

array([[1, 0],
       [0, 1]])

In [36]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
np.eye(4,5)#We dont need  to give column number bcoz identity matrix equal dimensions eg.4*4,2*2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

# 3. Generating Random number Arrays
NumPy also have many inbuilt functions to generate random function arrays.

## a. rand
Generate uniformly distributed random number over (0 , 1)

In [38]:
np.random.rand(2)

array([0.28252842, 0.26420221])

In [39]:
np.random.rand(3,3)

array([[0.10064234, 0.20214256, 0.49179872],
       [0.4261354 , 0.41565662, 0.81576379],
       [0.68406969, 0.82744482, 0.79588608]])

## b.randn
Generate normally distributed standard normal distribution(random numbers).

In [40]:
np.random.randn(2)

array([-0.52668565, -1.80801812])

In [41]:
np.random.randn(4,3)

array([[-0.29803361,  0.13285612,  0.89097283],
       [ 2.00900238, -0.07827254,  0.56167081],
       [-0.41202687, -0.40102048,  0.68727664],
       [-0.30163828,  0.38981558,  1.69346393]])

## c. randint
Generate random integer over given range.

In [42]:
np.random.randint(50,100)#if we dont mention number that how many number we want then it give by defoult single number

81

In [43]:
np.random.randint(50,100,10)

array([76, 93, 98, 72, 91, 91, 97, 98, 80, 63])

# Array Attributes and Methods

In [44]:
array1=np.arange(20)
print(array1)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


## a. shape
It give us number of rows and number of columns.

In [45]:
array1.shape#it give as number of rows and numbers of column

(20,)

## b. reshape
Change the original shape dimensions of the array

In [46]:
arr=array1.reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [47]:
arr=array1.reshape(5,3)#It dont give us matrix bcoz total number of rows and column are not match

ValueError: cannot reshape array of size 20 into shape (5,3)

In [48]:
arr.shape

(5, 4)

In [49]:
arr.shape[0]#0 gives rows number 1 gives column number

5

## max,min,argmax,argmin
max(),min() finding the maximum and minimum value.

argmax(),argmin() for index of max and min of elements. 

In [50]:
random_array1=np.random.randint(1,50,10)
random_array1

array([16,  7, 35, 34, 22, 21, 43, 37, 21, 45])

In [51]:
random_array1.max()

45

In [52]:
random_array1.argmax()

9

In [53]:
random_array1.min()

7

In [54]:
random_array1.argmin()

1

## dtype
To get the data type of the object in the array

similar method: np.result_type()

In [55]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [56]:
array1.dtype

dtype('int32')

In [57]:
np.result_type(array1)

dtype('int32')

In [58]:
array2=np.arange(1,10,1.25,dtype=np.int64)
array2

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [59]:
array3=np.arange(1,10,1.25,dtype=np.float64)
array3

array([1.  , 2.25, 3.5 , 4.75, 6.  , 7.25, 8.5 , 9.75])

## type()
type() returns class type of an object.

In [60]:
type(array1)

numpy.ndarray

In [61]:
array1.dtype#it will give inside the array data type give by dtype

dtype('int32')